var zh_cn = {

    view_detail:'查看详情',
    index_introduce1:'真正的魅力，源于内心对自己的认同。<br/>寻找个人风格的过程就是寻找自己的过程。<br/>不仅在于你的服装、外表、气质，<br/>也同样藏着你对自我审视的态度。<br/>无论你是属于哪一种风格，<br/>PACO TORA都是你展现自我最好的选择。',
    index_introduce2:'PACO TORA，一个来自西班牙的著名设计师品牌。<br/>我们希望带给您最好产品及服务，并渴望成为您真诚的朋友。',
    club_txt:'你不是插在花瓶里供人欣赏的静物，而是蔓延在草原上随风起舞的旋律。',
    club_scan:'扫码关注并回复hola，<br/>来这里找到同类及享受更多PT福利！',
    product_series:'系列',
    product_series1_p:'你可以是任何角色，但是没有任何角色可以定义你。',
    product_series2_p:'你想通过口才来表现你的有趣，还不如让你的包包来告诉他们。',
    product_series3_p:'时尚终将被时间过滤，而经典是永不过时的时尚。',
    viewMore:'了解更多 >>',
    brandDynamic:'品牌动态<p>Brand Dynamic</p>',
    brandStory:'品牌故事<p>Brand Story</p>',
    brandHistory:'品牌历程<p>Brand History</p>',
    brandStrength:'品牌实力<p>Brand Strength</p>',
    contactUs1:'广州图拉米拉贸易有限公司',
    contactUs2:'020-62903830转8813  ',
    contactUs3:'广东省广州市花都区金狮大道10号',
    contactUs4:'PT.BRAND@pacotora.com'
},
    en_US = {
        view_detail:'view more',
        index_introduce1:'Real charm comes from ones own heart.<br/> The process of finding personal style is the process of finding oneself<br/> It does not only depend on clothes, looks, or temperament,<br/> But also on the latent ability to self-reflect.<br/>Whatever your style may be<br/> PACO TORA is your best choice for presenting the real you.',
        index_introduce2:'PACO TORA ,a famous designer brand from Spain.<br/>Our aim is to bring you the best products and services, and we desire to be your true friend.',
        club_txt:'You are not a retreat to be appreciated in a vase,<br/>But a melody that spreads across the grassland.',
        club_scan:'Scan code to  follow and reply ”hola”<br/>Become a friend and enjoy more PT benefits here!',
        product_series:'Series',
        product_series1_p:'You can  play any role, but no role can define you.',
        product_series2_p:'For those who go against the tide of fashion and play with their own personality',
        product_series3_p:'Fashion changes over time, but classics never go out of style.',
        viewMore:'learn more >>',
        brandDynamic:'Brand Dynamic',
        brandStory:'Brand Story',
        brandHistory:'Brand History',
        brandStrength:'Brand Strength',
        contactUs1:'GUANGZHOU DOLAMY <br/>TRADING CO.,LTD',
        contactUs2:'020-62903830 EXT.8813  ',
        contactUs3:'NO.10 JINSHI AVENUE EAST, <br/>SHILING TOWN,HUADU DISTRICT, <br/>GUANGZHOU CITY GUANG DONG',
        contactUs4:'PT.BRAND@pacotora.com'
}